/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as CommunityTheatreIdRouteImport } from './routes/community/$theatreId'
import { Route as MoviesMovieIdRouteImport } from './routes/movies/$movieId'
import { Route as TheatresIndexRouteImport } from './routes/theatres/index'
import { Route as TheatresTheatreIdRouteImport } from './routes/theatres/$theatreId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminFoodRouteImport } from './routes/_authenticated/admin/food'
import { Route as AuthenticatedAdminMoviesRouteImport } from './routes/_authenticated/admin/movies'
import { Route as AuthenticatedAdminPollsRouteImport } from './routes/_authenticated/admin/polls'
import { Route as AuthenticatedAdminShowsRouteImport } from './routes/_authenticated/admin/shows'
import { Route as AuthenticatedAdminTheatreAccessRouteImport } from './routes/_authenticated/admin/theatre-access'
import { Route as AuthenticatedAdminTheatresRouteImport } from './routes/_authenticated/admin/theatres'
import { Route as AuthenticatedBookShowIdRouteImport } from './routes/_authenticated/book/$showId'
import { Route as AuthenticatedBookingBookingIdRouteImport } from './routes/_authenticated/booking/$bookingId'
import { Route as AuthenticatedTheatreIndexRouteImport } from './routes/_authenticated/theatre/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => AuthRoute,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityTheatreIdRoute = CommunityTheatreIdRouteImport.update({
  id: '/community/$theatreId',
  path: '/community/$theatreId',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const TheatresIndexRoute = TheatresIndexRouteImport.update({
  id: '/theatres/',
  path: '/theatres/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheatresTheatreIdRoute = TheatresTheatreIdRouteImport.update({
  id: '/theatres/$theatreId',
  path: '/theatres/$theatreId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminFoodRoute = AuthenticatedAdminFoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMoviesRoute =
  AuthenticatedAdminMoviesRouteImport.update({
    id: '/movies',
    path: '/movies',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPollsRoute = AuthenticatedAdminPollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminShowsRoute = AuthenticatedAdminShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTheatreAccessRoute =
  AuthenticatedAdminTheatreAccessRouteImport.update({
    id: '/theatre-access',
    path: '/theatre-access',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTheatresRoute =
  AuthenticatedAdminTheatresRouteImport.update({
    id: '/theatres',
    path: '/theatres',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedBookShowIdRoute = AuthenticatedBookShowIdRouteImport.update({
  id: '/book/$showId',
  path: '/book/$showId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingBookingIdRoute =
  AuthenticatedBookingBookingIdRouteImport.update({
    id: '/booking/$bookingId',
    path: '/booking/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTheatreIndexRoute =
  AuthenticatedTheatreIndexRouteImport.update({
    id: '/theatre/',
    path: '/theatre/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/bookings': typeof AuthenticatedBookingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/community/$theatreId': typeof CommunityTheatreIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/theatres/$theatreId': typeof TheatresTheatreIdRoute
  '/community/': typeof CommunityIndexRoute
  '/theatres/': typeof TheatresIndexRoute
  '/admin/food': typeof AuthenticatedAdminFoodRoute
  '/admin/movies': typeof AuthenticatedAdminMoviesRoute
  '/admin/polls': typeof AuthenticatedAdminPollsRoute
  '/admin/shows': typeof AuthenticatedAdminShowsRoute
  '/admin/theatre-access': typeof AuthenticatedAdminTheatreAccessRoute
  '/admin/theatres': typeof AuthenticatedAdminTheatresRoute
  '/book/$showId': typeof AuthenticatedBookShowIdRoute
  '/booking/$bookingId': typeof AuthenticatedBookingBookingIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/theatre/': typeof AuthenticatedTheatreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/community/$theatreId': typeof CommunityTheatreIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/theatres/$theatreId': typeof TheatresTheatreIdRoute
  '/community': typeof CommunityIndexRoute
  '/theatres': typeof TheatresIndexRoute
  '/admin/food': typeof AuthenticatedAdminFoodRoute
  '/admin/movies': typeof AuthenticatedAdminMoviesRoute
  '/admin/polls': typeof AuthenticatedAdminPollsRoute
  '/admin/shows': typeof AuthenticatedAdminShowsRoute
  '/admin/theatre-access': typeof AuthenticatedAdminTheatreAccessRoute
  '/admin/theatres': typeof AuthenticatedAdminTheatresRoute
  '/book/$showId': typeof AuthenticatedBookShowIdRoute
  '/booking/$bookingId': typeof AuthenticatedBookingBookingIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/theatre': typeof AuthenticatedTheatreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/community/$theatreId': typeof CommunityTheatreIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/theatres/$theatreId': typeof TheatresTheatreIdRoute
  '/community/': typeof CommunityIndexRoute
  '/theatres/': typeof TheatresIndexRoute
  '/_authenticated/admin/food': typeof AuthenticatedAdminFoodRoute
  '/_authenticated/admin/movies': typeof AuthenticatedAdminMoviesRoute
  '/_authenticated/admin/polls': typeof AuthenticatedAdminPollsRoute
  '/_authenticated/admin/shows': typeof AuthenticatedAdminShowsRoute
  '/_authenticated/admin/theatre-access': typeof AuthenticatedAdminTheatreAccessRoute
  '/_authenticated/admin/theatres': typeof AuthenticatedAdminTheatresRoute
  '/_authenticated/book/$showId': typeof AuthenticatedBookShowIdRoute
  '/_authenticated/booking/$bookingId': typeof AuthenticatedBookingBookingIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/theatre/': typeof AuthenticatedTheatreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/bookings'
    | '/auth/callback'
    | '/auth/confirm'
    | '/community/$theatreId'
    | '/movies/$movieId'
    | '/theatres/$theatreId'
    | '/community/'
    | '/theatres/'
    | '/admin/food'
    | '/admin/movies'
    | '/admin/polls'
    | '/admin/shows'
    | '/admin/theatre-access'
    | '/admin/theatres'
    | '/book/$showId'
    | '/booking/$bookingId'
    | '/admin/'
    | '/theatre/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/bookings'
    | '/auth/callback'
    | '/auth/confirm'
    | '/community/$theatreId'
    | '/movies/$movieId'
    | '/theatres/$theatreId'
    | '/community'
    | '/theatres'
    | '/admin/food'
    | '/admin/movies'
    | '/admin/polls'
    | '/admin/shows'
    | '/admin/theatre-access'
    | '/admin/theatres'
    | '/book/$showId'
    | '/booking/$bookingId'
    | '/admin'
    | '/theatre'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/bookings'
    | '/auth/callback'
    | '/auth/confirm'
    | '/community/$theatreId'
    | '/movies/$movieId'
    | '/theatres/$theatreId'
    | '/community/'
    | '/theatres/'
    | '/_authenticated/admin/food'
    | '/_authenticated/admin/movies'
    | '/_authenticated/admin/polls'
    | '/_authenticated/admin/shows'
    | '/_authenticated/admin/theatre-access'
    | '/_authenticated/admin/theatres'
    | '/_authenticated/book/$showId'
    | '/_authenticated/booking/$bookingId'
    | '/_authenticated/admin/'
    | '/_authenticated/theatre/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  CommunityTheatreIdRoute: typeof CommunityTheatreIdRoute
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
  TheatresTheatreIdRoute: typeof TheatresTheatreIdRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  TheatresIndexRoute: typeof TheatresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof AuthRoute
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$theatreId': {
      id: '/community/$theatreId'
      path: '/community/$theatreId'
      fullPath: '/community/$theatreId'
      preLoaderRoute: typeof CommunityTheatreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theatres/': {
      id: '/theatres/'
      path: '/theatres'
      fullPath: '/theatres/'
      preLoaderRoute: typeof TheatresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theatres/$theatreId': {
      id: '/theatres/$theatreId'
      path: '/theatres/$theatreId'
      fullPath: '/theatres/$theatreId'
      preLoaderRoute: typeof TheatresTheatreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/food': {
      id: '/_authenticated/admin/food'
      path: '/food'
      fullPath: '/admin/food'
      preLoaderRoute: typeof AuthenticatedAdminFoodRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/movies': {
      id: '/_authenticated/admin/movies'
      path: '/movies'
      fullPath: '/admin/movies'
      preLoaderRoute: typeof AuthenticatedAdminMoviesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/polls': {
      id: '/_authenticated/admin/polls'
      path: '/polls'
      fullPath: '/admin/polls'
      preLoaderRoute: typeof AuthenticatedAdminPollsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/shows': {
      id: '/_authenticated/admin/shows'
      path: '/shows'
      fullPath: '/admin/shows'
      preLoaderRoute: typeof AuthenticatedAdminShowsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/theatre-access': {
      id: '/_authenticated/admin/theatre-access'
      path: '/theatre-access'
      fullPath: '/admin/theatre-access'
      preLoaderRoute: typeof AuthenticatedAdminTheatreAccessRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/theatres': {
      id: '/_authenticated/admin/theatres'
      path: '/theatres'
      fullPath: '/admin/theatres'
      preLoaderRoute: typeof AuthenticatedAdminTheatresRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/book/$showId': {
      id: '/_authenticated/book/$showId'
      path: '/book/$showId'
      fullPath: '/book/$showId'
      preLoaderRoute: typeof AuthenticatedBookShowIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/booking/$bookingId': {
      id: '/_authenticated/booking/$bookingId'
      path: '/booking/$bookingId'
      fullPath: '/booking/$bookingId'
      preLoaderRoute: typeof AuthenticatedBookingBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/theatre/': {
      id: '/_authenticated/theatre/'
      path: '/theatre'
      fullPath: '/theatre/'
      preLoaderRoute: typeof AuthenticatedTheatreIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminFoodRoute: typeof AuthenticatedAdminFoodRoute
  AuthenticatedAdminMoviesRoute: typeof AuthenticatedAdminMoviesRoute
  AuthenticatedAdminPollsRoute: typeof AuthenticatedAdminPollsRoute
  AuthenticatedAdminShowsRoute: typeof AuthenticatedAdminShowsRoute
  AuthenticatedAdminTheatreAccessRoute: typeof AuthenticatedAdminTheatreAccessRoute
  AuthenticatedAdminTheatresRoute: typeof AuthenticatedAdminTheatresRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminFoodRoute: AuthenticatedAdminFoodRoute,
    AuthenticatedAdminMoviesRoute: AuthenticatedAdminMoviesRoute,
    AuthenticatedAdminPollsRoute: AuthenticatedAdminPollsRoute,
    AuthenticatedAdminShowsRoute: AuthenticatedAdminShowsRoute,
    AuthenticatedAdminTheatreAccessRoute: AuthenticatedAdminTheatreAccessRoute,
    AuthenticatedAdminTheatresRoute: AuthenticatedAdminTheatresRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedBookShowIdRoute: typeof AuthenticatedBookShowIdRoute
  AuthenticatedBookingBookingIdRoute: typeof AuthenticatedBookingBookingIdRoute
  AuthenticatedTheatreIndexRoute: typeof AuthenticatedTheatreIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedBookShowIdRoute: AuthenticatedBookShowIdRoute,
  AuthenticatedBookingBookingIdRoute: AuthenticatedBookingBookingIdRoute,
  AuthenticatedTheatreIndexRoute: AuthenticatedTheatreIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConfirmRoute: AuthConfirmRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  CommunityTheatreIdRoute: CommunityTheatreIdRoute,
  MoviesMovieIdRoute: MoviesMovieIdRoute,
  TheatresTheatreIdRoute: TheatresTheatreIdRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  TheatresIndexRoute: TheatresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
